(define (problem universal_FOON)

(:domain universal_FOON)

(:init
	(under ice_cubes table)
	(on table ice_cubes)
	(in glass air)
	(under glass table)
	(on table glass)
	(in bottle vodka)
	(under vodka bottle)
	(in bottle tomato_juice)
	(under tomato_juice bottle)
	(is-whole lemon)
	(under lemon table)
	(on table lemon)
	(in bottle worcestershire_sauce)
	(under worcestershire_sauce bottle)
	(in bottle tabasco_sauce)
	(under tabasco_sauce bottle)
	(in shaker salt)
	(under salt shaker)
	(in shaker pepper)
	(under pepper shaker)
	(under stirrer table)
	(on table stirrer)
	(is-whole celery_stalk)
	(under celery_stalk table)
	(on table celery_stalk)
)

(:goal (and
	(in glass celery_stalk)
	(under glass table)
	(on table glass)
))

)